<?php

namespace Database\Seeders;

use App\Models\Customer;
use Illuminate\Database\Seeder;

class CustomerSeeder extends Seeder
{
    public function run(): void
    {
        $customers = [
            [
                'customer_number' => 'CUST-001',
                'name' => 'أحمد محمد العلي',
                'email' => 'ahmed.ali@email.com',
                'phone' => '+96891234567',
                'address' => 'مسقط، سلطنة عمان',
                'nationality' => 'عماني',
                'customer_type' => 'INDIVIDUAL',
                'id_number' => '1234567890',
                'status' => 'ACTIVE',
                'registration_date' => '2023-01-15',
                'guarantor_name' => 'محمد أحمد العلي',
                'guarantor_phone' => '+96891234568',
                'guarantor_id' => '0987654321',
                'notes' => 'عميل ممتاز، يدفع في الوقت المحدد',
                'rating' => 5,
            ],
            [
                'customer_number' => 'CUST-002',
                'name' => 'شركة البناء الحديث',
                'email' => 'info@modernbuilding.om',
                'phone' => '+96824567890',
                'address' => 'الرستاق، سلطنة عمان',
                'nationality' => 'عماني',
                'customer_type' => 'COMPANY',
                'commercial_record' => 'CR-123456',
                'status' => 'ACTIVE',
                'registration_date' => '2023-02-20',
                'guarantor_name' => 'سالم أحمد البوسعيدي',
                'guarantor_phone' => '+96824567891',
                'guarantor_id' => '1122334455',
                'notes' => 'شركة كبيرة، عقود متعددة',
                'rating' => 4,
            ],
            [
                'customer_number' => 'CUST-003',
                'name' => 'فاطمة سالم الحارثي',
                'email' => 'fatima.harithi@email.com',
                'phone' => '+96837890123',
                'address' => 'صلالة، سلطنة عمان',
                'nationality' => 'عماني',
                'customer_type' => 'INDIVIDUAL',
                'id_number' => '2233445566',
                'status' => 'ACTIVE',
                'registration_date' => '2023-03-10',
                'notes' => 'عميلة جديدة، تحتاج متابعة',
                'rating' => 3,
            ],
            [
                'customer_number' => 'CUST-004',
                'name' => 'مؤسسة النهضة التجارية',
                'email' => 'contact@nahda.om',
                'phone' => '+96845678901',
                'address' => 'نزوى، سلطنة عمان',
                'nationality' => 'عماني',
                'customer_type' => 'COMPANY',
                'commercial_record' => 'CR-789012',
                'status' => 'INACTIVE',
                'registration_date' => '2022-12-05',
                'notes' => 'شركة متوقفة عن العمل',
                'warnings' => 'تأخير في الدفع',
                'rating' => 2,
            ],
            [
                'customer_number' => 'CUST-005',
                'name' => 'خالد عبدالله الشنفري',
                'email' => 'khalid.shanfari@email.com',
                'phone' => '+96856789012',
                'address' => 'صور، سلطنة عمان',
                'nationality' => 'عماني',
                'customer_type' => 'INDIVIDUAL',
                'id_number' => '3344556677',
                'status' => 'ACTIVE',
                'registration_date' => '2023-04-15',
                'guarantor_name' => 'عبدالله خالد الشنفري',
                'guarantor_phone' => '+96856789013',
                'guarantor_id' => '4455667788',
                'notes' => 'عميل موثوق، دفع مقدم',
                'rating' => 4,
            ],
            [
                'customer_number' => 'CUST-006',
                'name' => 'شركة المقاولات المتحدة',
                'email' => 'info@unitedcontractors.om',
                'phone' => '+96867890123',
                'address' => 'البريمي، سلطنة عمان',
                'nationality' => 'عماني',
                'customer_type' => 'COMPANY',
                'commercial_record' => 'CR-345678',
                'status' => 'ACTIVE',
                'registration_date' => '2023-05-20',
                'notes' => 'شركة نشطة، عقود كبيرة',
                'rating' => 5,
            ],
            [
                'customer_number' => 'CUST-007',
                'name' => 'مريم أحمد الكندي',
                'email' => 'mariam.kindi@email.com',
                'phone' => '+96878901234',
                'address' => 'مسقط، سلطنة عمان',
                'nationality' => 'عماني',
                'customer_type' => 'INDIVIDUAL',
                'id_number' => '5566778899',
                'status' => 'ACTIVE',
                'registration_date' => '2023-06-10',
                'notes' => 'عميلة ممتازة، توصية من عميل آخر',
                'rating' => 5,
            ],
            [
                'customer_number' => 'CUST-008',
                'name' => 'شركة التطوير العمراني',
                'email' => 'contact@urbandevelopment.om',
                'phone' => '+96889012345',
                'address' => 'السيب، سلطنة عمان',
                'nationality' => 'عماني',
                'customer_type' => 'COMPANY',
                'commercial_record' => 'CR-901234',
                'status' => 'INACTIVE',
                'registration_date' => '2022-11-15',
                'notes' => 'شركة تحت التصفية',
                'warnings' => 'مشاكل مالية',
                'rating' => 1,
            ],
            [
                'customer_number' => 'CUST-009',
                'name' => 'عبدالرحمن سالم البوسعيدي',
                'email' => 'abdulrahman.busaidi@email.com',
                'phone' => '+96890123456',
                'address' => 'الرستاق، سلطنة عمان',
                'nationality' => 'عماني',
                'customer_type' => 'INDIVIDUAL',
                'id_number' => '6677889900',
                'status' => 'ACTIVE',
                'registration_date' => '2023-07-05',
                'guarantor_name' => 'سالم عبدالرحمن البوسعيدي',
                'guarantor_phone' => '+96890123457',
                'guarantor_id' => '7788990011',
                'notes' => 'عميل جديد، يحتاج متابعة',
                'rating' => 3,
            ],
            [
                'customer_number' => 'CUST-010',
                'name' => 'شركة الإنشاءات المتقدمة',
                'email' => 'info@advancedconstruction.om',
                'phone' => '+96801234567',
                'address' => 'مسقط، سلطنة عمان',
                'nationality' => 'عماني',
                'customer_type' => 'COMPANY',
                'commercial_record' => 'CR-567890',
                'status' => 'ACTIVE',
                'registration_date' => '2023-08-15',
                'notes' => 'شركة كبيرة، عقود حكومية',
                'rating' => 5,
            ],
        ];

        foreach ($customers as $customer) {
            Customer::create($customer);
        }

        $this->command->info('✅ تم إنشاء ' . count($customers) . ' عميل بنجاح!');
    }
}
