<?php

namespace Database\Seeders;

use App\Models\Employee;
use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $employees = [
            [
                'employee_number' => 'EMP001',
                'name' => 'أحمد محمد العلي',
                'arabic_name' => 'أحمد محمد العلي',
                'email' => 'ahmed.ali@company.com',
                'phone' => '+96891234567',
                'mobile' => '+96891234567',
                'address' => 'شارع السلطان قابوس، حي الغبرة',
                'city' => 'مسقط',
                'nationality' => 'عماني',
                'date_of_birth' => '1985-05-15',
                'gender' => 'male',
                'marital_status' => 'married',
                'id_number' => '1234567890',
                'passport_number' => 'A1234567',
                'position' => 'مدير المبيعات',
                'department' => 'المبيعات',
                'manager' => 'سارة أحمد',
                'location' => 'مسقط',
                'hire_date' => '2022-01-15',
                'contract_type' => 'full_time',
                'work_schedule' => '8:00 AM - 5:00 PM',
                'status' => 'active',
                'basic_salary' => 1500.00,
                'allowances' => 300.00,
                'total_salary' => 1800.00,
                'currency' => 'ر.ع',
                'payment_method' => 'bank_transfer',
                'bank_account' => '1234567890123456',
            ],
            [
                'employee_number' => 'EMP002',
                'name' => 'فاطمة سالم الكندي',
                'arabic_name' => 'فاطمة سالم الكندي',
                'email' => 'fatima.kindi@company.com',
                'phone' => '+96892345678',
                'mobile' => '+96892345678',
                'address' => 'شارع السلطان قابوس، حي القرم',
                'city' => 'مسقط',
                'nationality' => 'عماني',
                'date_of_birth' => '1990-08-20',
                'gender' => 'female',
                'marital_status' => 'single',
                'id_number' => '2345678901',
                'passport_number' => 'A2345678',
                'position' => 'محاسبة',
                'department' => 'المالية',
                'manager' => 'محمد عبدالله',
                'location' => 'مسقط',
                'hire_date' => '2021-08-20',
                'contract_type' => 'full_time',
                'work_schedule' => '8:00 AM - 5:00 PM',
                'status' => 'active',
                'basic_salary' => 1000.00,
                'allowances' => 200.00,
                'total_salary' => 1200.00,
                'currency' => 'ر.ع',
                'payment_method' => 'bank_transfer',
                'bank_account' => '2345678901234567',
            ],
            [
                'employee_number' => 'EMP003',
                'name' => 'خالد أحمد الشنفري',
                'arabic_name' => 'خالد أحمد الشنفري',
                'email' => 'khalid.shanfari@company.com',
                'phone' => '+96893456789',
                'mobile' => '+96893456789',
                'address' => 'شارع السلطان قابوس، حي السيب',
                'city' => 'صلالة',
                'nationality' => 'عماني',
                'date_of_birth' => '1988-03-10',
                'gender' => 'male',
                'marital_status' => 'married',
                'id_number' => '3456789012',
                'passport_number' => 'A3456789',
                'position' => 'مطور برمجيات',
                'department' => 'التقنية',
                'manager' => 'علي محمد',
                'location' => 'صلالة',
                'hire_date' => '2023-03-10',
                'contract_type' => 'full_time',
                'work_schedule' => '8:00 AM - 5:00 PM',
                'status' => 'active',
                'basic_salary' => 1300.00,
                'allowances' => 200.00,
                'total_salary' => 1500.00,
                'currency' => 'ر.ع',
                'payment_method' => 'bank_transfer',
                'bank_account' => '3456789012345678',
            ],
            [
                'employee_number' => 'EMP004',
                'name' => 'مريم عبدالرحمن البلوشي',
                'arabic_name' => 'مريم عبدالرحمن البلوشي',
                'email' => 'mariam.balushi@company.com',
                'phone' => '+96894567890',
                'mobile' => '+96894567890',
                'address' => 'شارع السلطان قابوس، حي المطار',
                'city' => 'مسقط',
                'nationality' => 'عماني',
                'date_of_birth' => '1992-11-05',
                'gender' => 'female',
                'marital_status' => 'single',
                'id_number' => '4567890123',
                'passport_number' => 'A4567890',
                'position' => 'أخصائية موارد بشرية',
                'department' => 'الموارد البشرية',
                'manager' => 'نورا السالمي',
                'location' => 'مسقط',
                'hire_date' => '2022-11-05',
                'contract_type' => 'full_time',
                'work_schedule' => '8:00 AM - 5:00 PM',
                'status' => 'active',
                'basic_salary' => 900.00,
                'allowances' => 200.00,
                'total_salary' => 1100.00,
                'currency' => 'ر.ع',
                'payment_method' => 'bank_transfer',
                'bank_account' => '4567890123456789',
            ],
            [
                'employee_number' => 'EMP005',
                'name' => 'سعد محمد الغافري',
                'arabic_name' => 'سعد محمد الغافري',
                'email' => 'saad.ghafri@company.com',
                'phone' => '+96895678901',
                'mobile' => '+96895678901',
                'address' => 'شارع السلطان قابوس، حي بوشر',
                'city' => 'نزوى',
                'nationality' => 'عماني',
                'date_of_birth' => '1995-01-20',
                'gender' => 'male',
                'marital_status' => 'single',
                'id_number' => '5678901234',
                'passport_number' => 'A5678901',
                'position' => 'مندوب مبيعات',
                'department' => 'المبيعات',
                'manager' => 'أحمد محمد العلي',
                'location' => 'نزوى',
                'hire_date' => '2023-01-20',
                'contract_type' => 'full_time',
                'work_schedule' => '8:00 AM - 5:00 PM',
                'status' => 'active',
                'basic_salary' => 700.00,
                'allowances' => 200.00,
                'total_salary' => 900.00,
                'currency' => 'ر.ع',
                'payment_method' => 'bank_transfer',
                'bank_account' => '5678901234567890',
            ],
        ];

        foreach ($employees as $employee) {
            // Check if employee with same email already exists
            if (!Employee::where('email', $employee['email'])->exists()) {
                Employee::create($employee);
            } else {
                $this->command->warn('⚠️ الموظف بالبريد الإلكتروني ' . $employee['email'] . ' موجود بالفعل. تم تخطيه.');
            }
        }

        $this->command->info('✅ تم إنشاء ' . count($employees) . ' موظف بنجاح!');
    }
}
